### ISSUE TITLE
Error on loadChallenges function if configured URL has a missing trailing slash

### ISSUE THREAD

**Issue by eloipeloux** [aeyoll/pow-captcha-for-prestashop#3]
cURL error sends back : `Could not resolve host: captcha.kaizen-agency.frGetChallenges`

If challenges aren't loaded on previous method call, no error nor Exception is raised. Thus `array_shift` on `null` and nothing like so is prompted.

**Comment by aeyoll** [comment]
You need to put a / at the end of the host in the configuration, won't fix :)
